import 'package:cloud_firestore/cloud_firestore.dart';
import 'package:firebase_storage/firebase_storage.dart';
import '../models/story_model.dart';
import 'firebase_storage_service.dart';
import 'dart:io';

class StoryService {
  final FirebaseFirestore _firestore = FirebaseFirestore.instance;
  final FirebaseStorageService _storageService = FirebaseStorageService();
  final String collection = 'stories';

  /// Fetch all active stories (not expired)
  Stream<List<StoryModel>> getActiveStories() {
    final now = DateTime.now();
    return _firestore
        .collection(collection)
        .where('expiresAt', isGreaterThan: now.millisecondsSinceEpoch)
        .orderBy('expiresAt', descending: true)
        .snapshots()
        .map((snapshot) {
      return snapshot.docs.map((doc) => StoryModel.fromMap(doc.data(), id: doc.id)).toList();
    });
  }

  /// Post a new story
  Future<void> postStory({
    required String userId,
    required String userName,
    String? userAvatar,
    required File mediaFile,
    StoryType type = StoryType.image,
    String? caption,
  }) async {
    // 1. Upload media to storage
    final String folder = 'stories/$userId';
    final downloadUrl = await _storageService.uploadFile(mediaFile, folder);

    if (downloadUrl == null) throw Exception("Failed to upload story media");

    // 2. Create story document
    final now = DateTime.now();
    final expiresAt = now.add(const Duration(hours: 24));
    
    final story = StoryModel(
      id: '', // Generated by Firestore
      userId: userId,
      userName: userName,
      userAvatar: userAvatar,
      type: type,
      content: downloadUrl,
      caption: caption,
      createdAt: now,
      expiresAt: expiresAt,
      viewedBy: [],
      reactions: [],
    );

    await _firestore.collection(collection).add(story.toMap());
  }

  /// Mark story as viewed
  Future<void> viewStory(String storyId, String userId) async {
    await _firestore.collection(collection).doc(storyId).update({
      'viewedBy': FieldValue.arrayUnion([userId]),
    });
  }

  /// Delete a story
  Future<void> deleteStory(String storyId) async {
    await _firestore.collection(collection).doc(storyId).delete();
  }
}
